version: "3"
services:
  airprint-relay:
    build: .
    container_name: airprint-relay
    volumes:
      - /opt/cups/config:/config
      - /opt/cups/services:/services
    environment:
      - CUPSADMIN=admin
      - CUPSPASSWORD=admin
    network_mode: "host"
    ports:
      - "631:631"
    restart: unless-stopped
    # example routing setup for traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airprint-relay.rule=Host(`airprint-relay.example.org`)"
      - "traefik.http.services.airprint-relay.loadbalancer.server.port=631"
      - "traefik.http.services.airprint-relay.loadbalancer.passhostheader=false"
