version: "3"
services:
  airprint-relay:
    build: .
    container_name: airprint-relay
    volumes:
      - /opt/cups/config:/config
      - /opt/cups/services:/services
    environment:
      - CUPSADMIN=admin
      - CUPSPASSWORD=admin
    network_mode: "host"
    ports:
      - "631:631"
    restart: unless-stopped
