name: build multiarch release image

on:
  release:
    types: [published]
#  push:
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
#        with:
#          fallback: 1.0.0
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag agoodcontainer/airprint-relay:${{ steps.previoustag.outputs.tag }} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
